services:
  postgres:
    container_name: pgsql_inf15979
    image: postgres
    volumes:
      - ./ddl/postgres/create_dbs.sql:/docker-entrypoint-initdb.d/create_dbs.sql
      - ./ddl/postgres/db_hackerrank.sql:/docker-entrypoint-initdb.d/db_hackerrank.sql
      - ./ddl/postgres/db_autos.sql:/docker-entrypoint-initdb.d/db_autos.sql
      - ./ddl/postgres/db_banking.sql:/docker-entrypoint-initdb.d/db_banking.sql
      - ./ddl/postgres/db_f1.sql:/docker-entrypoint-initdb.d/db_f1.sql
      - ./ddl/postgres/db_silberschatz.sql:/docker-entrypoint-initdb.d/db_silberschatz.sql
    environment:
      POSTGRES_USER: "aluno"
      POSTGRES_PASSWORD: "elmasri"
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: elmasri
      MYSQL_USER: "aluno"
      MYSQL_DATABASE: default_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ddl/mysql:/docker-entrypoint-initdb.d:ro

volumes:
  mysql_data: